services:
  app:
    build: ./engine
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - ./engine:/app
    links:
      - db
    depends_on:
      - db
    environment:
      WAIT_HOSTS: test_mongodb:27017
    networks:
      - mongo
  db:
    image: mongo:latest
    container_name: mongodb
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=cryptocurrency_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./engine/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    networks:
      - mongo
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      #- ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      #- ME_CONFIG_BASICAUTH_USERNAME=root
      #- ME_CONFIG_BASICAUTH_PASSWORD=pass
    #volumes:
      #- $HOME/uzrnem/database/mongo_db
    ports:
      - 8002:8081
    networks:
      - mongo
    depends_on:
      - db
  
networks:
  mongo:
    driver: bridge
      
